### ISSUE TITLE
Clarify relationship between kmmarkeringen and vaarwegvakken

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#17]
`kmmarkeringen` has a `vwk_id` attribute that probably refers to objects in the `vaarwegvakken` table, with the key there probably also being `vwk_id`. However, when establishing a relationship, there are 456 `MarkerPost` objects derived from `vaarwegvakken` objects that do not have a valid reference. Is there any more info/confirmation that the relationship is like that?

**Comment by thorsten-reitz** [comment]
The question aims at adding the `MarkerPost.route` and `InlandWaterway.post` references.

**Comment by HerzovanderWal** [comment]
Thorsten lets call to lign up.

**Comment by HerzovanderWal** [comment]
@thorsten-reitz  - I have asked my colleges to register and connect to GitHub. 
I see the issues/conclusions you mention. Are they a problem in this first itteration? What do you need? What can I do?

**Comment by HerzovanderWal** [comment]
The issue is recognized in the TN-Roads datasets as well. The asumption vwk-id is the key! The missing connectors are probebly the result off the difference between traffic-nodes where the transport-networks and roads really cross and common nodes, where roadsegment (vaarwegvakken) are connected to each other. This is probably also the case in Roads. For now please ask Peter S. to deliver the complete set off nodes.
