### ISSUE TITLE
Create alignment for Elevation data

### ISSUE THREAD

**Issue by thorsten-reitz** [codefornl/INSPIRE#30]
This task's objective is to generate INSPIRE GML for the Elevation 4.0 Schema from the following source data sets:

-	AHN3 (Hoogte)
-	AHN2 (Hoogte)
-	AHN1 25 meter (Hoogte)

We will not republish the existing elevation data sets, but instead create GML objects that references the original data sets at the existing granularity.

The results of this task are…:

-	a detailed conceptual mapping documentation
-	One or more hale studio transformation projects
-	the transformed data sets, published as a download services

**Comment by thorsten-reitz** [comment]
As a start, we will work with the AHN3 5m data set. There are several access points for this data set which delibver 5m rasters as GeoTIFFs, e.g.:

https://www.pdok.nl/nl/ahn3-downloads
http://nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/5ba9e4c6-ed93-42f2-8b1a-a12f8a287b9b

If possible, we will use the information in the metadata to directly create the GML objects.

A TIN is currently not generated/provided.

**Comment by JohannaOtt** [comment]
updates:
1. I got a reply in the Thematic Cluster but that did not really explain the issue - I asked for clarification again.

2. Julián could not really help out so @thorsten-reitz reached out to Jordi Escriu who should be able to deliver information on this.

7. the data provider sent an answer today: "Concerning your first question, this is indeed an error in the shapefile. The unit on the left should have the label 10DZ1 instead of 10DZ2.
The AHN units are based on the Top 10 map sheets (Top10 kaartbladen) of the Dutch land register (Kadaster), and are used to divide the AHN2 into 
equal and acceptable sizes for downloading purposes.  
I am not sure how the shapefile  "AHN units" was produced. For the intended use, which is finding the correct unit of the AHN2 to download, 
it is irrelevant whether a unit consists of 4 vertices or more than 4. So, 4 vertices are expected, but more vertices are not relevant.
Kind regards,
Ingrid Alkemade"
I will ask if the dataset will be adapted accordingly.

**Comment by JohannaOtt** [comment]
update:

6. the questions was answered in the Thematic Cluster. We can put information on the interpolation method in supplementaryInformation (either in the metadata on dataset level or in the metadata attribute of ElevationGridCoverage if we want to deliver it on spatial object level. I must have misinterpreted this paragraphe of the Data Specification.

Nevertheless, the metadata attribute on dataset level should be used in case the data does not exactly fit the definition of DSM or DTM ("Since real elevation data sets have very often discrepancies to what it is considered as a pure DTM or DSM (e.g. presence of any dynamic features, limitations due to the data capture process of data coming from a specific provider), these deviations should be explained in the metadata (supplementalInformation metadata element), in order to show what is really included within the DEM.") (DS section 5.5.1.2.1.).

**Comment by JohannaOtt** [comment]
Current versions of the AHN2 and AHN3 alignment including examples for INSPIRE GML datasets have been added to the repository.
Please note, that for both transformations, it is necessary to pass the coverageid of the coverage that should be used for the GML dataset as project variable. Both source WCS contain four coverages.

The source for the tiles used has been changed from the Shapefile used so far to a WFS that is delivering the tiles in between. The value "10dz2" still appears twice in the source-attribute "UNIT", but according to my comment from January 29th, the data provider should now be aware of that.

During the implementation, I found that the offsetVector information for AHN 2 and AHN 3 deviate strongly from each other. They should be checked by an expert being responsible for the WCS creation:
- AHN2: https://geodata.nationaalgeoregister.nl/ahn2/wcs?VERSION=2.0.1&SERVICE=WCS&REQUEST=describecoverage&coverageid=ahn2_05m_int, one offsetVector is "<gml:offsetVector srsName="http://www.opengis.net/def/crs/EPSG/0/28992">29.325000 0</gml:offsetVector>"
- AHN3: https://geodata.nationaalgeoregister.nl/ahn3/wcs?VERSION=2.0.1&SERVICE=WCS&REQUEST=describecoverage&coverageid=ahn3_5m_dsm, one offsetVector "<gml:offsetVector srsName="http://www.opengis.net/def/crs/EPSG/0/28992">5.000000 0</gml:offsetVector>"

Publishing the created GML files as WFS is currently blocked by issues of deegree handling the gml:RectifiedGrid object (ING-1804). We will publish the datasets as WFSs as soon as that is fixed.

Delivering WCS data in a WFS is allowed but not recommended: https://inspire.ec.europa.eu/forum/pages/view/116444/how-to-deal-with-huge-volume-of-coverage-data-case-1-delivery-through-predefined-datasets Currently, the specifications are aligned in order to reach INSPIRE- and OGC-compliant Coverage delivery at the same time. Once these changes are accepted, the delivery of the EL data should be changed from the currently realised GML-handling to WCS.
